/**:
  ros__parameters:
    use_sim_time: true
    frame_id: base_link
    odom_frame_id: odom
    publish_tf: true
    initial_pose: "0 0 -1 0 0 0"
    publish_null_when_lost: true
    approx_sync: true
    approx_sync_max_interval: 0.025
    topic_queue_size: 2
    sync_queue_size: 5
    qos: 1
    qos_camera_info: 1
    wait_for_transform: 0.2
    expected_update_rate: 0.0
    "Odom/Strategy": "1"
    "Odom/ResetCountdown": "0"
    "Reg/Force3DoF": "false"
    "Vis/FeatureType": "1"
    "Vis/MaxFeatures": "1000"
    "Vis/MinInliers": "20"
    "Vis/MaxDepth": "14.5"
    "Vis/CorType": "1"
    "Vis/CorFlowMinEigThreshold": "0.000001"
    "SIFT/ContrastThreshold": "0.01"
