<?xml version="1.0"?>
<package format="3">

  <name>flight_state_monitor</name>

  <version>0.0.1</version>

  <description>
    ROS 2 Flight State Monitor for MAVROS / ArduSub.
  </description>

  <maintainer email="ahmed@example.com">
    Ahmed
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>mavros_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
